---
title: "Components"
author: "John Coene"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Components}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(htmltools)
```

```{r, echo=FALSE}
div(
  class = "row",
  div(
    class = "col-md-4",
    div(
      class = "thumbnail",
      div(
        class = "caption",
        h3("aenvironment"),
        p("Easily add environments to aframer packages and visualisations."),
        p(
          a(
            class = "btn btn-default",
            tags$i(class = "fa fa-desktop"), " Site",
            href = "https://aenvironment.john-coene.com/"
          )
        )
      )
    )
  ),
  div(
    class = "col-md-4",
    div(
      class = "thumbnail",
      div(
        class = "caption",
        h3("aextras"),
        p("Extras components for aframer."),
        p(
          a(
            class = "btn btn-default",
            tags$i(class = "fa fa-desktop"), " Site",
            href = "https://aextras.john-coene.com/"
          )
        )
      )
    )
  ),
  div(
    class = "col-md-4",
    div(
      class = "thumbnail",
      div(
        class = "caption",
        h3("aparticle"),
        p("Particle system for aframer."),
        p(
          a(
            class = "btn btn-default",
            tags$i(class = "fa fa-desktop"), " Site",
            href = "https://aparticle.john-coene.com/"
          )
        )
      )
    )
  )
)

div(
  class = "row",
  div(
    class = "col-md-4",
    div(
      class = "thumbnail",
      div(
        class = "caption",
        h3("aphysics"),
        p("Physics component for aframer."),
        p(
          a(
            class = "btn btn-default",
            tags$i(class = "fa fa-desktop"), " Site",
            href = "https://aphysics.john-coene.com/"
          )
        )
      )
    )
  ),
  div(
    class = "col-md-4",
    div(
      class = "thumbnail",
      div(
        class = "caption",
        h3("apoint"),
        p("Point component for aframer."),
        p(
          a(
            class = "btn btn-default",
            tags$i(class = "fa fa-desktop"), " Site",
            href = "https://apoint.john-coene.com/"
          )
        )
      )
    )
  ),
  div(
    class = "col-md-4",
    div(
      class = "thumbnail",
      div(
        class = "caption",
        h3("ashake"),
        p("shake2show for aframer."),
        p(
          a(
            class = "btn btn-default",
            tags$i(class = "fa fa-desktop"), " Site",
            href = "https://ashake.john-coene.com/"
          )
        )
      )
    )
  )
)

div(
  class = "row",
  div(
    class = "col-md-4",
    div(
      class = "thumbnail",
      div(
        class = "caption",
        h3("acurve"),
        p("Curve components for aframer."),
        p(
          a(
            class = "btn btn-default",
            tags$i(class = "fa fa-desktop"), " Site",
            href = "https://acurve.john-coene.com/"
          )
        )
      )
    )
  ),
  div(
    class = "col-md-4",
    div(
      class = "thumbnail",
      div(
        class = "caption",
        h3("apath"),
        p("Path component for aframer."),
        p(
          a(
            class = "btn btn-default",
            tags$i(class = "fa fa-desktop"), " Site",
            href = "https://apath.john-coene.com/"
          )
        )
      )
    )
  ),
  div(
    class = "col-md-4",
    div(
      class = "thumbnail",
      div(
        class = "caption",
        h3("acubemap"),
        p("Cubemap component for aframer."),
        p(
          a(
            class = "btn btn-default",
            tags$i(class = "fa fa-desktop"), " Site",
            href = "https://acubemap.john-coene.com/"
          )
        )
      )
    )
  )
)

div(
  class = "row",
  div(
    class = "col-md-4",
    div(
      class = "thumbnail",
      div(
        class = "caption",
        h3("alookat"),
        p("Look-at component for aframer."),
        p(
          a(
            class = "btn btn-default",
            tags$i(class = "fa fa-github"), " Github",
            href = "https://github.com/JohnCoene/alookat"
          )
        )
      )
    )
  ) 
)
```
