---
title: "Packages"
author: "John Coene"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Packages}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(htmltools)
```

Below are some packages built on top of `aframer`.

```{r, echo=FALSE}
div(
  class = "row",
  div(
    class = "col-md-4",
    div(
      class = "thumbnail",
      img(
        src = "https://aforce.john-coene.com/logo.png",
        class = "responsive-img img-responsive"
      ),
      div(
        class = "caption",
        h3("aforce"),
        p("An aframer package to build Virtual Reality force directed graphs."),
        p(
          a(
            class = "btn btn-default",
            tags$i(class = "fa fa-desktop"), " Site",
            href = "http://aforce.john-coene.com/"
          ),
          a(
            class = "btn btn-primary btn-blue",
            tags$i(class = "fa fa-eye"), " Demo",
            href = "http://aforce.john-coene.com/example.html"
          )
        )
      )
    )
  ),
  div(
    class = "col-md-4",
    div(
      class = "thumbnail",
      img(
        src = "https://ascatter.john-coene.com/logo.png",
        class = "responsive-img img-responsive"
      ),
      div(
        class = "caption",
        h3("ascatter"),
        p("An aframer package to build Virtual Reality 3D scatter plots."),
        p(
          a(
            class = "btn btn-default",
            tags$i(class = "fa fa-desktop"), " Site",
            href = "http://ascatter.john-coene.com/"
          ),
          a(
            class = "btn btn-primary btn-blue",
            tags$i(class = "fa fa-eye"), " Demo",
            href = "http://ascatter.john-coene.com/example.html"
          )
        )
      )
    )
  ),
  div(
    class = "col-md-4",
    div(
      class = "thumbnail",
      img(
        src = "https://acharts.john-coene.com/logo.png",
        class = "responsive-img img-responsive"
      ),
      div(
        class = "caption",
        h3("acharts"),
        p("An aframer package to build Virtual Reality 3D graphs plots."),
        p(
          a(
            class = "btn btn-default",
            tags$i(class = "fa fa-desktop"), " Site",
            href = "http://acharts.john-coene.com/"
          ),
          a(
            class = "btn btn-primary btn-blue",
            tags$i(class = "fa fa-eye"), " Demo",
            href = "http://acharts.john-coene.com/example.html"
          )
        )
      )
    )
  )
)
```
